# https://travis-ci.org/
language: node_js
node_js:
  - '5'
script: 'npm run verify'
install:
  - 'travis_retry npm install'
addons:
  firefox: 'latest'
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
